In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from Functions import*

In [2]:
# Load data 
path = '/data/'
application = pd.read_csv(path + 'application_train.csv') 
bureau = pd.read_csv(path + 'bureau.csv') 
prev_application = pd.read_csv(path + 'previous_application.csv')
application_test = pd.read_csv(path + 'application_test.csv')

# Cleaning + FE

## application_train

In [3]:
application_fe = preprocess_application(application)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:6610: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [4]:
application_fe.shape

(307507, 84)

In [5]:
application_fe.head(5)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,CREDIT_GOODS_RATIO,CREDIT_GOODS_DIFF,CREDIT_TERM,DAYS_EMPLOYED_RATIO,FLAG_CONTACTS_SUM,CNT_NON_CHILDREN,CHILDREN_INCOME_RATIO,PER_CAPITA_INCOME,FLAG_REGIONS,SUM_FLAGS_DOCUMENTS
0,100002,1,Cash loans,M,0,1,0,202500.0,406597.5,24700.5,...,1.158397,55597.50001,16.461104,0.067329,4,1.0,0.0,101250.0,0,1
1,100003,0,Cash loans,F,0,0,0,270000.0,1293502.5,35698.5,...,1.145199,164002.50001,36.234085,0.070862,4,2.0,0.0,90000.0,0,1
2,100004,0,Revolving loans,M,1,1,0,67500.0,135000.0,6750.0,...,1.000000,0.00001,20.000000,0.011814,5,1.0,0.0,33750.0,0,0
3,100006,0,Cash loans,F,0,1,0,135000.0,312682.5,29686.5,...,1.052803,15682.50001,10.532818,0.159905,3,2.0,0.0,45000.0,0,1
4,100007,0,Cash loans,M,0,1,0,121500.0,513000.0,21865.5,...,1.000000,0.00001,23.461618,0.152418,3,1.0,0.0,60750.0,2,1

## bureau

In [6]:
bureau_fe = preprocess_bureau(bureau)

In [7]:
bureau_fe.shape

(305811, 13)

In [8]:
bureau_fe.head()

,BUREAU_COUNT,BUREAU_TYPES_COUNT,BUREAU_ACTIVE_LOANS_PCT,BUREAU_PAST_DUE_LOANS_PCT,BUREAU_TOTAL_DEBT,BUREAU_TOTAL_CREDIT,BUREAU_TOTAL_OVERDUE,BUREAU_CREDIT_PROL_AVG,BUREAU_OVERDUE_COUNT,BUREAU_DAYS_DIFF_AVG,BUREAU_AVG_TYPES_COUNT,BUREAU_RATIO_DEBT_CREDIT,BUREAU_RATIO_OVERDUE_DEBT
SK_ID_CURR,,,,,,,,,,,,,
100001,7,1,0.428571,0.0,596686.5,1453365.000,0.0,0.0,0,217.571429,7.0,0.410555,0.0
100002,8,2,0.250000,0.0,245781.0,865055.565,0.0,0.0,0,166.750000,4.0,0.284122,0.0
100003,4,2,0.250000,0.0,0.0,1017400.500,0.0,0.0,0,495.000000,2.0,0.000000,0.0
100004,2,1,0.000000,0.0,0.0,189037.800,0.0,0.0,0,459.000000,2.0,0.000000,0.0
100005,3,2,0.666667,0.0,568408.5,657126.000,0.0,0.0,0,103.666667,1.5,0.864992,0.0

In [9]:
bureau_fe.to_csv('bureau_fe.csv')

## previous_application

In [10]:
prev_application_fe = preprocess_prevapp(prev_application)

In [11]:
prev_application_fe.shape

(338857, 18)

In [12]:
prev_application_fe.head()

,PREVAPP_SK_ID_PREV_COUNT,PREVAPP_AMT_ANNUITY_LAST,PREVAPP_AMT_APPLICATION_LAST,PREVAPP_AMT_CREDIT_LAST,PREVAPP_AMT_DOWN_PAYMENT_LAST,PREVAPP_AMT_GOODS_PRICE_LAST,PREVAPP_FLAG_LAST_APPL_PER_CONTRACT_LAST,PREVAPP_DAYS_FIRST_DUE_LAST,PREVAPP_DAYS_LAST_DUE_1ST_VERSION_LAST,PREVAPP_DAYS_LAST_DUE_LAST,PREVAPP_AMT_DECLINED_LAST,PREVAPP_AMT_CREDIT_GOODS_RATIO_LAST,PREVAPP_AMT_CREDIT_GOODS_DIFF_LAST,PREVAPP_AMT_CREDIT_APPLICATION_RATIO_LAST,PREVAPP_CREDIT_DOWNPAYMENT_RATIO_LAST,PREVAPP_GOOD_DOWNPAYMET_RATIO_LAST,PREVAPP_ANNUITY_LAST,PREVAPP_ANNUITY_GOODS_LAST
SK_ID_CURR,,,,,,,,,,,,,,,,,,
100001,1,3951.000,24835.5,23787.0,2520.0,24835.5,1,-1709.0,-1499.0,-1619.0,1048.5,0.957782,-1048.5,1.044079,0.105940,0.101468,2973.371283,3104.433619
100002,1,9251.775,179055.0,179055.0,0.0,179055.0,1,-565.0,125.0,-25.0,0.0,1.000000,0.0,1.000000,0.000000,0.000000,7460.621891,7460.621891
100003,3,6737.310,68809.5,68053.5,6885.0,68809.5,1,-2310.0,-1980.0,-1980.0,756.0,0.989013,-756.0,1.011109,0.101170,0.100059,5671.120274,5734.120222
100004,1,5357.250,24282.0,20106.0,4860.0,24282.0,1,-784.0,-694.0,-724.0,4176.0,0.828021,-4176.0,1.207699,0.241719,0.200148,5026.487434,6070.484824
100005,2,4813.200,44617.5,40153.5,4464.0,44617.5,1,-706.0,-376.0,-466.0,4464.0,0.899950,-4464.0,1.111173,0.111173,0.100050,3346.122212,3718.121902

In [13]:
prev_application_fe.to_csv('previous_application_fe.csv')

# Merge & Preprocess final data

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PowerTransformer
from sklearn.pipeline import Pipeline
import pickle

In [16]:
data = merge_data(application_fe, bureau_fe, prev_application_fe)

In [17]:
data.shape

(307507, 115)

In [18]:
# Prepare preprocessing for numerical variables
categorical_var = [col for col in data.columns if data.dtypes[col] == 'object']
numerical_var = [col for col in data.columns if (col not in categorical_var) and (col != 'TARGET') and (col != 'SK_ID_CURR')]

pp_num_pipeline = Pipeline([
            ('imp_med', SimpleImputer(missing_values=np.nan, strategy='median')),
            ('scaler', StandardScaler()),
            ('transformer',PowerTransformer(method='yeo-johnson') )
                        ])

pp_num_pipeline.fit(data[numerical_var])

Pipeline(steps=[('imp_med', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler()),
                ('transformer', PowerTransformer())])

In [19]:
# save pipeline for numerical variables preprocessing
pickle.dump(pp_num_pipeline, open('preprocess_numerical.pkl','wb'))

In [20]:
data_pp = preprocessing_data(data)

In [21]:
data_pp.shape

(307507, 35)

In [22]:
data_pp.head()

,DAYS_BIRTH,INCOME_ANNUITY_DIFF,PREVAPP_AMT_ANNUITY_LAST,ANNUITY_INCOME_RATIO,FLAG_EMP_PHONE,BUREAU_TOTAL_DEBT,REGION_POPULATION_RELATIVE,REG_CITY_NOT_LIVE_CITY,CODE_GENDER_F,REGION_RATING_CLIENT_W_CITY,...,DAYS_REGISTRATION,PREVAPP_ANNUITY_GOODS_LAST,FLAG_DOCUMENT_3,BUREAU_DAYS_DIFF_AVG,DAYS_ID_PUBLISH,BUREAU_ACTIVE_LOANS_PCT,PREVAPP_DAYS_LAST_DUE_1ST_VERSION_LAST,NAME_INCOME_TYPE_Working,BUREAU_TOTAL_CREDIT,CREDIT_TERM
0,1.559095,0.762617,-0.222534,-0.593390,0.468701,-0.128410,0.074130,-0.29121,0,-0.046238,...,0.262142,-0.245409,0.639051,-0.196349,0.670954,-0.487097,-0.142889,1,-0.230652,-0.621325
1,-0.204894,1.273775,-0.681998,-0.432407,0.468701,-0.839479,-1.741164,-0.29121,1,-2.106158,...,1.182220,-0.245423,0.639051,1.365703,1.607912,-0.487097,-0.588387,0,-0.052646,1.705985
2,-0.709025,-1.301768,-0.969722,-0.963213,0.468701,-0.839479,-0.864368,-0.29121,0,-0.046238,...,0.060999,-0.245420,-1.564821,1.246666,0.428122,-1.647821,-0.310389,1,-1.220488,-0.120571
3,-0.700129,-0.300614,1.498388,0.632722,0.468701,-0.332046,-1.120378,-0.29121,1,-0.046238,...,-1.307022,-0.245354,0.639051,0.053442,0.485142,0.012663,-0.211547,1,-0.116026,-1.539895
4,-0.900010,-0.411882,1.089898,0.217022,0.468701,-0.839479,0.784985,-0.29121,0,-0.046238,...,0.044791,-0.245334,-1.564821,-1.715492,-0.196916,-1.647821,-0.321270,1,-1.295190,0.324797

In [23]:
# Select variables and filter data for dashboard
selected_features = ['DAYS_BIRTH', 'INCOME_ANNUITY_DIFF', 'PREVAPP_AMT_ANNUITY_LAST',
       'ANNUITY_INCOME_RATIO', 'FLAG_EMP_PHONE', 'BUREAU_TOTAL_DEBT',
       'REGION_POPULATION_RELATIVE', 'REG_CITY_NOT_LIVE_CITY',
       'REGION_RATING_CLIENT_W_CITY', 'PREVAPP_AMT_CREDIT_GOODS_DIFF_LAST',
       'REG_CITY_NOT_WORK_CITY', 'BUREAU_RATIO_DEBT_CREDIT',
       'DAYS_LAST_PHONE_CHANGE', 'EXT_SOURCE_1', 'PREVAPP_SK_ID_PREV_COUNT',
       'CREDIT_GOODS_RATIO', 'BUREAU_COUNT', 'NAME_EDUCATION_TYPE','AMT_GOODS_PRICE',
       'EXT_SOURCE_2', 'DAYS_EMPLOYED_RATIO', 'PREVAPP_AMT_DECLINED_LAST',
       'DAYS_REGISTRATION', 'PREVAPP_ANNUITY_GOODS_LAST', 'FLAG_DOCUMENT_3',
       'BUREAU_DAYS_DIFF_AVG', 'DAYS_ID_PUBLISH', 'BUREAU_ACTIVE_LOANS_PCT',
       'PREVAPP_DAYS_LAST_DUE_1ST_VERSION_LAST',
       'BUREAU_TOTAL_CREDIT', 'CREDIT_TERM']

data_selection = data[['TARGET'] + selected_features]
data_selection.to_csv('data_compare_clients.csv')

# Fit and save final model

In [24]:
import lightgbm as lgbm

# final model tuned with Pycaret
model_lgbm = lgbm.LGBMClassifier(bagging_fraction=0.7, bagging_freq=6, boosting_type='gbdt',
               class_weight='balanced', colsample_bytree=1.0,
               feature_fraction=0.5, importance_type='split', learning_rate=0.1,
               max_depth=-1, min_child_samples=66, min_child_weight=0.001,
               min_split_gain=0.4, n_estimators=90, n_jobs=-1, num_leaves=90,
               objective=None, random_state=123, reg_alpha=0.0005,
               reg_lambda=0.1, silent=True, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [25]:
model_lgbm.fit(data_pp, data['TARGET'])

[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] feature_fraction is set=0.5, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7

LGBMClassifier(bagging_fraction=0.7, bagging_freq=6, class_weight='balanced',
               feature_fraction=0.5, min_child_samples=66, min_split_gain=0.4,
               n_estimators=90, num_leaves=90, random_state=123,
               reg_alpha=0.0005, reg_lambda=0.1)

In [27]:
# save preprocessing
pickle.dump(model_lgbm, open('lgbm_model.pkl','wb'))